package nextstep.signup.validator

enum class ValidateResult {
    SUCCESS,
    INVALID_LENGTH_USERNAME,
    INVALID_FORMAT_USERNAME,
    INVALID_FORMAT_EMAIL,
    INVALID_LENGTH_PASSWORD,
    INVALID_FORMAT_PASSWORD,
    NOT_MATCH_PASSWORD,
}
